//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HledaciAlgoritmy.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("objekty")]
        public string Vykreslovani {
            get {
                return ((string)(this["Vykreslovani"]));
            }
            set {
                this["Vykreslovani"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _Vykreslovani {
            get {
                return ((bool)(this["_Vykreslovani"]));
            }
            set {
                this["_Vykreslovani"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VychoziCesta {
            get {
                return ((string)(this["VychoziCesta"]));
            }
            set {
                this["VychoziCesta"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CestaObr1 {
            get {
                return ((string)(this["CestaObr1"]));
            }
            set {
                this["CestaObr1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CestaObr2 {
            get {
                return ((string)(this["CestaObr2"]));
            }
            set {
                this["CestaObr2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CestaObr3 {
            get {
                return ((string)(this["CestaObr3"]));
            }
            set {
                this["CestaObr3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CestaObr4 {
            get {
                return ((string)(this["CestaObr4"]));
            }
            set {
                this["CestaObr4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gray")]
        public global::System.Drawing.Color BarvaCesta {
            get {
                return ((global::System.Drawing.Color)(this["BarvaCesta"]));
            }
            set {
                this["BarvaCesta"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192, 64, 0")]
        public global::System.Drawing.Color BarvaProhledany {
            get {
                return ((global::System.Drawing.Color)(this["BarvaProhledany"]));
            }
            set {
                this["BarvaProhledany"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int tb1 {
            get {
                return ((int)(this["tb1"]));
            }
            set {
                this["tb1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int tb2 {
            get {
                return ((int)(this["tb2"]));
            }
            set {
                this["tb2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Images\\obj1.png|Start|0|True|True|1")]
        public string start {
            get {
                return ((string)(this["start"]));
            }
            set {
                this["start"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Images\\obj2.png|Konec|0|True|False|0")]
        public string konec {
            get {
                return ((string)(this["konec"]));
            }
            set {
                this["konec"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Images\\obj3.png|Zed|0|False|False|0")]
        public string zed {
            get {
                return ((string)(this["zed"]));
            }
            set {
                this["zed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Images\\obj4.png|Cesta|0|True|False|0")]
        public string silnice {
            get {
                return ((string)(this["silnice"]));
            }
            set {
                this["silnice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Images\\obj5.png|Les|80|True|False|0")]
        public string Obj5 {
            get {
                return ((string)(this["Obj5"]));
            }
            set {
                this["Obj5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Images\\obj6.png|Voda|0|False|False|0")]
        public string Obj6 {
            get {
                return ((string)(this["Obj6"]));
            }
            set {
                this["Obj6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Images\\obj7.png|None|0|True|False|0")]
        public string Obj7 {
            get {
                return ((string)(this["Obj7"]));
            }
            set {
                this["Obj7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Images\\obj8.png|None|0|True|False|0")]
        public string Obj8 {
            get {
                return ((string)(this["Obj8"]));
            }
            set {
                this["Obj8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ObrazkyObjs {
            get {
                return ((string)(this["ObrazkyObjs"]));
            }
            set {
                this["ObrazkyObjs"] = value;
            }
        }
    }
}
